[package]
name = "fedi-credential-sdk-protocol"
version = "0.1.0"
edition = "2021"
description = "Rust-facing, stateless credential protocol API for issuing and verifying partially blinded credentials."
license = "MIT"
repository = "https://github.com/fedibtc/credential-sdk"
readme = "../../README.md"

[dependencies]
blind-rsa-signatures = "0.17.1"
hex = "0.4.3"
nostr = "0.44.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_json_canonicalizer = "0.3.2"
serde_with = { version = "3", features = ["base64"] }
sha2 = "0.10"
thiserror = "2"
