[package]
name = "fedi-credential-sdk-wasm"
version = "0.1.1"
edition = "2021"
description = "WebAssembly bindings for the fedi credential protocol crate."
license = "MIT"
repository = "https://github.com/fedibtc/credential-sdk"
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fedi-credential-sdk-protocol = { path = "../protocol", version = "0.1.1" }
getrandom = { version = "0.4.2", features = ["wasm_js"] }
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
wasm-bindgen = "0.2"
